#
# Makefile for kernel BIF framework.
#
obj-$(CONFIG_BIF)			+= bif-core.o
obj-$(CONFIG_BIF_QPNP)			+= qpnp-bsi.o

KBUILD_CFLAGS	+=-Wno-unused-const-variable
KBUILD_CFLAGS	+=-Wno-misleading-indentation
